# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.1-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      # - image: circleci/mysql:5.7-ram
      #
      # - image: redis:2.8.19

    steps:
      - checkout
      - deploy:
          name: Deploy to host if branch is master
          command: |
            sudo apt-get update
            sudo apt-get -qq install git-ftp
            echo "'_$(git status -uno --porcelain | wc -l)_'"
            git status -uno --porcelain
            echo "${FTP_USER}"   
            echo "${FTP_PWD}" 
            echo ${FTP_LOCATION}
            git config git-ftp.user ${FTP_USER}
            git config git-ftp.url ${FTP_URL}/${RELEASE_FOLDER_NAME}_${CIRCLE_BUILD_NUM}
            git config git-ftp.password ${FTP_PWD}
            git ftp init
      #- run: ssh -oStrictHostKeyChecking=no -v {SSH_USER}@${SSH_URL} "./deploy.sh ${RELEASE_FOLDER_NAME}_${CIRCLE_BUILD_NUM} ${CIRCLE_BUILD_NUM} 'staging_shopware' "